### ISSUE TITLE
Any hidden menu to show all available themes?

### ISSUE THREAD

**Issue by fr3fou** [briano1905/typings#18]
Are there any plans to have some kind of menu that shows all the available themes / be able to change to them quickly?

**Comment by briano1905** [comment]
Currently no, maybe in the future if i figure out a nice way to do it.

**Comment by Miodec** [comment]
Hey, just made a pull request #32 that adds this feature.

**Comment by briano1905** [comment]
Miodec that theme selector looks amazing how can I not pull. Great job and thank you so much!
