### ISSUE TITLE
Question about XHR vs fetch()

### ISSUE THREAD

**Issue by fr3fou** [briano1905/typings#23]
hiya!

I noticed that in some places of the code, such as

https://github.com/briano1905/typings/blob/ccadb7420d8ed1ac07ff5c41ba547d2b648d3a9b/main.js#L254-L266

you use an `XMLHttpRequest`, whereas in other places, such as

https://github.com/briano1905/typings/blob/ccadb7420d8ed1ac07ff5c41ba547d2b648d3a9b/main.js#L268-L282

you use `fetch`. Any reason why? If you'd like I could quickly fix it up and make them both use `fetch` :>

**Comment by briano1905** [comment]
There are absolutely no reason for that. I'm just being inconsistent for no reason. And you can change it to fetch if you'd like

**Comment by fr3fou** [comment]
Fixed in #24
