### ISSUE TITLE
Suggestion: Remove the redo button competely and make 'tab' the redo key

### ISSUE THREAD

**Issue by Miodec** [briano1905/typings#35]
Just a thought - instead of pressing tab + enter to restart the test you could just remove the button, make it a bit cleaner and just have the tab key restart the test by adding a key listener and checking for tab keycode.

**Comment by jakergrossman** [comment]
The only problem is that excludes users who need to use tab to navigate the page  from having full functionality on the site.

**Comment by briano1905** [comment]
As @jakergrossman said
