### ISSUE TITLE
Can we get a redo hotkey?

### ISSUE THREAD

**Issue by GreenPigeon** [briano1905/typings#51]
I kinda want a redo button instead of doing the herculean task of moving my hand to my mouse and pressing m1. But fr I would really like one thx.

**Comment by Miodec** [comment]
tab+enter

**Comment by briemens** [comment]
I've created a pull request #55 to restart the typing test using `ESC`.

**Comment by briano1905** [comment]
Pull request #55 merged

Now you can use `esc` to restart typing test
