### ISSUE TITLE
[Feature Request] Favicon/Website Icon

### ISSUE THREAD

**Issue by SubhamSatyajeet** [briano1905/typings#66]
Just a small icon for the website. Everything else is just perfect.

**Comment by herohamp** [comment]
Maybe just a small lowercase t in the roboto font?

**Comment by SubhamSatyajeet** [comment]
@herohamp Sounds great!

**Comment by herohamp** [comment]
```
var canvas = document.createElement('canvas');
var ctx = canvas.getContext("2d");
canvas.width = 64;
canvas.height = 64;
canvas.style.position = "absolute";
canvas.style.visibility= "hidden";
ctx.font = "60px Roboto Mono";
ctx.textAlign = "center";
ctx.textBaseline = "middle"
ctx.fillStyle = window.getComputedStyle(document.getElementsByTagName("body")[0], null).getPropertyValue("background-color");
ctx.beginPath();
ctx.arc(32, 32, 32, 0, 2 * Math.PI);
ctx.fill();
ctx.fillStyle = window.getComputedStyle(document.getElementById("header"), null).getPropertyValue("color");
ctx.fillText("T",32,37);
ctx.fillRect(32,32,1,1);


var link = document.querySelector("link[rel*='icon']") || document.createElement('link');
    link.type = 'image/png';
    link.rel = 'shortcut icon';
    link.href = canvas.toDataURL();
    document.getElementsByTagName('head')[0].appendChild(link);
```

This is a quick prototype for the icon that i threw together, copy paste that into the javascript console and see how it looks for different theme, you will have to rerun the script on each new theme. I want some feedback before I made it a PR

**Comment by jakergrossman** [comment]
I would use a lowercase t to match the styling for the site.

```
ctx.fillText("t", 31, 34);
```

As well, I would suggest pulling the text and background colors from `text-display` and `typing-area` respectively. This makes it, in my opinion, represent each theme more accurately, since at the moment a lot of themes are just black on white or white on black, since the colors are taken from the header and the body. Great work overall, though!

**Comment by SubhamSatyajeet** [comment]
Have to agree with @jakergrossman here: Lowercase t looks better here. Bold also makes the lowercase letter look more prominent. I made the following changes:

`ctx.font = "Bold 56px Roboto Mono";`
`ctx.fillText("t", 32, 32);`

This is how it looks:

![image](https://user-images.githubusercontent.com/7932787/81505797-8d249980-930f-11ea-9161-70b530903813.png)
Edge Chromium, Light

![image](https://user-images.githubusercontent.com/7932787/81505998-0ffa2400-9311-11ea-9633-40038234872f.png)
Edge Chromium, Gruvbox

In Firefox, the favicon looks out of alignment with the baseline of the Website title font.
Could be how Firefox renders favicons by default. Still looks good, though.

![image](https://user-images.githubusercontent.com/7932787/81505811-b8a78400-930f-11ea-852d-865abdd1eaeb.png)
Firefox, Dark

![image](https://user-images.githubusercontent.com/7932787/81505862-120fb300-9310-11ea-90ed-42ecb12cbd05.png)
Firefox, Gruvbox

(All screenshots on Windows, 1080p, 125% scaling)

What do you guys think?

**Comment by herohamp** [comment]
i really like all of the suggestions, is someone going to put together a pull request with this or should I?

**Comment by SubhamSatyajeet** [comment]
I tried the above, but I think the colours of the heading and the page background should be used to colour the favicon letter and background.

![image](https://user-images.githubusercontent.com/7932787/81507960-80f40880-931e-11ea-9499-d7fdf72bea2c.png)
Edge Chromium, Gruvbox

IMO, using `text-display` and `typing-area` colours make it look a little worse than before, but it's personal preference.

There are two themes where the background is a pattern (1976/Vilebloom). Not sure what page background to use in those cases.

**Comment by herohamp** [comment]
I personally think that using `text-display` and `typing-area` looks slightly better and the themes look more different.

**Comment by SubhamSatyajeet** [comment]
Cool, thanks for making the PR!

**Comment by herohamp** [comment]
I have given up, I for some reason cannot get it to properly match the first loaded theme, it just always defaults to white. If someone get it working you're amazing. My repo is here https://github.com/herohamp/typings. I have tried everything I can think of including setTimeouts, onloads, observers, and base64ing the css so it loads instantly. The last idea would be to parse the css source code, but that would be so bloated.

**Comment by jakergrossman** [comment]
@herohamp I found a solution. The reason it wasn't working was because the site transitions between themes. `setFavicon()` was pulling colors from the beginning of the transition. If you add an event listener for `transitionend` on `body`, the Favicon will automatically update after each theme transition:

```
document.querySelector('body').addEventListener('transitionend', () =>
    setFavicon();
});
```
