### ISSUE TITLE
Request: Expand word range

### ISSUE THREAD

**Issue by jim-alexander** [briano1905/typings#78]
Iv been using your app pretty consistently for a few weeks now and I'm getting too familiar with your word set. Can you expand the range of words that you use.

**Comment by gregorioospina** [comment]
It would be nice if you could import a text or something to be typed out.

**Comment by jim-alexander** [comment]
I can type **nation** so fast now...

**Comment by jim-alexander** [comment]
English1000 exists, read the docs jim... thanks jim
