### ISSUE TITLE
New keyboard shortcut

### ISSUE THREAD

**Issue by theamanjs** [briano1905/typings#83]
I've been using typings.gg from last few days and loving it. However, I'm feeling that there can be some feature which will save a lot of time like keyboard shortcuts for themes and restart typing after it's done. Instead of using mouse for it keyboard shortcut will be more productive. Thank you for this amazing application.

**Comment by jakergrossman** [comment]
Is <kbd>Tab</kbd><kbd>Enter</kbd> too much? For themes, it's just typing in the name of the theme and hitting:

  - windows: <kbd>alt</kbd> + <kbd>t</kbd>
  - mac: <kbd>cmd</kbd> + <kbd>ctrl</kbd> + <kbd>t</kbd>
  - linux <kbd>super</kbd> + <kbd>ctrl</kbd> + <kbd>t</kbd> or <kbd>alt</kbd> + <kbd>t</kbd>

**Comment by surajhume** [comment]
just press ESC to restart typing.

**Comment by m-althaf** [comment]
> Is TabEnter too much? For themes, it's just typing in the name of the theme and hitting:
> 
> * windows: alt + t
> * mac: cmd + ctrl + t

I don't know about this but 
> * linux super + ctrl + t or alt + t

This doesn't work, also 
`Shift` `+` `Esc` opens task manager in brave

**Comment by jakergrossman** [comment]
<kbd>Alt</kbd><kbd>t</kbd> and <kbd>Super</kbd><kbd>Ctrl</kbd><kbd>t</kbd> is what's listed in the README, and works for me with Firefox on both my Ubuntu 20.04 and Manjaro installs.

**Comment by Ultrahalf** [comment]
@jakergrossman 

![output](https://user-images.githubusercontent.com/41832211/95807463-dc8c4d00-0d27-11eb-9047-2833403f0bb8.gif)

**Browser used:**
Brave
Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) unknown (64-bit)
**OS**: Arch

**Comment by m-althaf** [comment]
![output](https://user-images.githubusercontent.com/41832211/95808990-54a84200-0d2b-11eb-8316-5a70f26b7ec8.gif)

**browser:** Brave
Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) unknown (64-bit)

**OS:** Arch

>

**Comment by briemens** [comment]
> ![output](https://user-images.githubusercontent.com/41832211/95808990-54a84200-0d2b-11eb-8316-5a70f26b7ec8.gif)
> 
> **browser:** Brave
> Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) unknown (64-bit)
> 
> **OS:** Arch

Please take a careful look at the readme. It clearly explains how you have to use these shortcuts and it will answer your questions.

Hint: you have to type in a name of theme, language, etc before pressing the shortcut keys.

**Comment by m-althaf** [comment]
> 
> Please take a careful look at the readme. It clearly explains how you have to use these shortcuts and it will answer your questions.
> 
> Hint: you have to type in a name of theme, language, etc before pressing the shortcut keys.

oh sorry and thank you
