### ISSUE TITLE
[Language Request] Bengali/ বাংলা Language

### ISSUE THREAD

**Issue by iamrahatul** [briano1905/typings#86]
Hi.
Can you add **Bengali/ বাংলা** language, please?
There are two options if you consider adding the language.

1. Phonetic --_Types Bengali if you input English_
> You can look into this website or the app -
https://www.easybengalityping.com
https://www.omicronlab.com/avro-keyboard.html

2. Non-Phonetic -- _Bengali input only_

**Comment by jakergrossman** [comment]
(2) should be extremely easy to implement similarly to #62, #65. If you (or somebody else), could provide a list of common Bengali words, this could be done in 5 minutes.

**Comment by iamrahatul** [comment]
I added some Bengali words in text/random but couldn’t add lot more, here are 1000 Bengali words with English translations, if you want to add more. Or maybe if I have time I'll add them later.

https://1000mostcommonwords.com/1000-most-common-bengali-words
