### ISSUE TITLE
Could there be a way to customize theme without keyboard shortcuts? 

### ISSUE THREAD

**Issue by BlitzKraft** [briano1905/typings#9]
I am not sure if the shortcuts are being intercepted in the middle by my browser/desktop and am unable to change anything. I tried using it with no addons in the browser. I also tried changing my keyboard layout to mac, just to find out if that might help. It didn't. 

I am on Linux(Sabayon), using Firefox with BSPWM.

**Comment by briano1905** [comment]
Hi what you could do is copy these commands to the browser console:
`setTheme('olivia')`
`setLanguage('german')`
`setTypingMode('time')`
`setPunctuation('true')`
I know it's not the best solution but I don't plan to add any more UI element to the site for aesthetic reason

**Comment by BlitzKraft** [comment]
I tried that and works perfectly. Great work around. 

I'll need to find out where my key presses are being intercepted.
